name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    # Build Go CLI
    - name: Build CLI binaries
      run: |
        cd cli
        GOOS=linux GOARCH=amd64 go build -o fedmcp-linux-amd64 ./cmd/fedmcp
        GOOS=darwin GOARCH=amd64 go build -o fedmcp-darwin-amd64 ./cmd/fedmcp
        GOOS=darwin GOARCH=arm64 go build -o fedmcp-darwin-arm64 ./cmd/fedmcp
        GOOS=windows GOARCH=amd64 go build -o fedmcp-windows-amd64.exe ./cmd/fedmcp
    
    # Build Python package
    - name: Build Python package
      run: |
        cd core/python
        pip install build
        python -m build
    
    # Build TypeScript package
    - name: Build TypeScript package
      run: |
        cd core/typescript
        npm ci
        npm run build
        npm pack
    
    # Build Docker images
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push server image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        push: true
        tags: |
          ghcr.io/fedmcp/server:${{ github.ref_name }}
          ghcr.io/fedmcp/server:latest
    
    # Create GitHub Release
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cli/fedmcp-*
          core/python/dist/*
          core/typescript/*.tgz
        body: |
          ## FedMCP Release ${{ github.ref_name }}
          
          ### Installation
          
          **CLI**:
          ```bash
          # macOS (Intel)
          curl -L https://github.com/fedmcp/fedmcp/releases/download/${{ github.ref_name }}/fedmcp-darwin-amd64 -o fedmcp
          chmod +x fedmcp
          
          # macOS (Apple Silicon)
          curl -L https://github.com/fedmcp/fedmcp/releases/download/${{ github.ref_name }}/fedmcp-darwin-arm64 -o fedmcp
          chmod +x fedmcp
          
          # Linux
          curl -L https://github.com/fedmcp/fedmcp/releases/download/${{ github.ref_name }}/fedmcp-linux-amd64 -o fedmcp
          chmod +x fedmcp
          ```
          
          **Python**:
          ```bash
          pip install fedmcp==${{ github.ref_name }}
          ```
          
          **Docker**:
          ```bash
          docker pull ghcr.io/fedmcp/server:${{ github.ref_name }}
          ```
          
          ### Changelog
          See [CHANGELOG.md](https://github.com/fedmcp/fedmcp/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
        draft: false
        prerelease: ${{ contains(github.ref_name, 'rc') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}